global:
  scrape_interval: "10s"
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: openwrt
    static_configs:
      - targets:
          - 192.168.1.1:9100